# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a8ce42730ccf6ae0303e46393da88a8311db35b4ba562ea9f3b4d1f5f3f98ec6bc30e9af50f0b2bb6db0a2fa4849b995c3d4a28bb0a05193c413ba744d348c56

test:
  secret_key_base: 56d044582ca97df606f749b7395185d4e1abef3bb473f0868266d13223f61e4d8f0118de17ccd5dfdec9bda85772db41d452124d7be49ccf0026eb7b39d02d0a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
